local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 5
  publish_frequency: 10
  static_map: false

  width: 3
  height: 3

  resolution: 0.025

  rolling_window: true

plugins:
 - {name: footprint, type: "costmap_2d::FootprintLayer"}
 - {name: obstacles_layer, type: “costmap_2d::ObstacleLayer”}
 - {name: inflation_layer, type: “costmap_2d::InflationLayer”}