global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 1.0
  publish_frequency: 1.0 # default: 0
  static_map: true

  #width: 50
  #height: 50

  #origin_x: 50
  #origin_y: 50

  resolution: 0.025

plugins:

 - {name: static,type: “costmap_2d::StaticLayer”}
 - {name: inflation,type: “costmap_2d::InflationLayer”}
 - {name: obstacles,type: “costmap_2d::VoxelLayer”}