obstacle_range: 3.0
raytrace_range: 3.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[0.2,0.2], [-0.3,0.2], [-0.3,-0.2], [0.2,-0.2]]

inflation_radius: 0.35 # 35cm

transform_tolerance: 1.0
map_type: costmap
cost_scaling_factor: 100

max_obstacle_height: 1.0
min_obstacle_height: 0.05

inflation_layer:
  inflation_radius: 0.5

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

static:
  map_topic: map
  subscribe_to_updates: true